"""LLM service wrapper for Azure OpenAI chat and JSON mode completions."""

import json
import logging
from typing import TypeVar, Type
from pydantic import BaseModel, ValidationError
from openai import AzureOpenAI, OpenAIError, BadRequestError
from config import (
    AZURE_OPENAI_ENDPOINT,
    AZURE_OPENAI_API_KEY,
    AZURE_OPENAI_DEPLOYMENT,
    AZURE_OPENAI_API_VERSION,
    validate_config,
)

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)

_client = None


def get_azure_client() -> AzureOpenAI:
    """Initializes and returns a singleton AzureOpenAI client instance."""
    global _client
    if _client is not None:
        return _client

    is_valid, missing = validate_config()
    if not is_valid:
        raise ValueError(
            f"Azure OpenAI configuration is incomplete. Missing or invalid variables: {', '.join(missing)}. "
            "Please configure your .env file with your Azure AI Foundry / Azure OpenAI deployment details."
        )

    _client = AzureOpenAI(
        azure_endpoint=AZURE_OPENAI_ENDPOINT,
        api_key=AZURE_OPENAI_API_KEY,
        api_version=AZURE_OPENAI_API_VERSION,
    )
    return _client


def chat(messages: list[dict[str, str]], temperature: float = 0.7) -> str:
    """
    Executes a standard conversational chat completion with the Azure OpenAI model.

    Args:
        messages: List of message dictionaries with 'role' and 'content'.
        temperature: Sampling temperature (default 0.7).

    Returns:
        The text response generated by the model.
    """
    client = get_azure_client()
    try:
        try:
            response = client.chat.completions.create(
                model=AZURE_OPENAI_DEPLOYMENT,
                messages=messages,
                temperature=temperature,
            )
        except BadRequestError as e:
            # Handle models (e.g. gpt-5-mini, o1/o3) that only allow temperature=1.0 or default
            if "temperature" in str(e).lower():
                response = client.chat.completions.create(
                    model=AZURE_OPENAI_DEPLOYMENT,
                    messages=messages,
                    temperature=1.0,
                )
            else:
                raise

        content = response.choices[0].message.content or ""
        return content.strip()
    except OpenAIError as e:
        logger.error(f"Azure OpenAI API error during chat(): {e}")
        raise RuntimeError(f"Azure OpenAI API error: {str(e)}") from e
    except Exception as e:
        logger.error(f"Unexpected error during chat(): {e}")
        raise RuntimeError(f"Unexpected LLM error: {str(e)}") from e


def json_chat(
    messages: list[dict[str, str]],
    schema_model: Type[T],
    temperature: float = 0.2,
    max_retries: int = 1,
) -> T:
    """
    Executes a structured JSON chat completion, parsing and validating the output
    against the provided Pydantic schema model.

    Args:
        messages: List of message dicts. A system instruction containing 'JSON' is ensured.
        schema_model: The Pydantic model class to parse and validate response.
        temperature: Low temperature for reliable structured output (default 0.2).
        max_retries: Number of retries on JSON parsing or validation failure (default 1).

    Returns:
        An instance of schema_model.
    """
    client = get_azure_client()

    # Ensure at least one system message or instruction mentions the word "JSON"
    # as required by Azure OpenAI / OpenAI JSON mode.
    formatted_messages = list(messages)
    has_json_instruction = any(
        "json" in m.get("content", "").lower() for m in formatted_messages
    )
    if not has_json_instruction:
        formatted_messages.insert(
            0,
            {
                "role": "system",
                "content": "You are a helpful assistant that outputs only valid JSON strictly matching the requested format.",
            },
        )

    last_error = None
    use_temp_1 = False

    for attempt in range(max_retries + 1):
        try:
            curr_temp = 1.0 if use_temp_1 else (temperature if attempt == 0 else 0.0)
            try:
                response = client.chat.completions.create(
                    model=AZURE_OPENAI_DEPLOYMENT,
                    messages=formatted_messages,
                    temperature=curr_temp,
                    response_format={"type": "json_object"},
                )
            except BadRequestError as be:
                if "temperature" in str(be).lower():
                    use_temp_1 = True
                    response = client.chat.completions.create(
                        model=AZURE_OPENAI_DEPLOYMENT,
                        messages=formatted_messages,
                        temperature=1.0,
                        response_format={"type": "json_object"},
                    )
                else:
                    raise

            raw_content = response.choices[0].message.content or "{}"
            
            # Clean possible markdown block markers if present
            cleaned_content = raw_content.strip()
            if cleaned_content.startswith("```json"):
                cleaned_content = cleaned_content[7:]
            if cleaned_content.startswith("```"):
                cleaned_content = cleaned_content[3:]
            if cleaned_content.endswith("```"):
                cleaned_content = cleaned_content[:-3]
            cleaned_content = cleaned_content.strip()

            parsed_dict = json.loads(cleaned_content)
            validated_obj = schema_model.model_validate(parsed_dict)
            return validated_obj

        except (json.JSONDecodeError, ValidationError) as e:
            last_error = e
            logger.warning(
                f"JSON parse/validation failure on attempt {attempt + 1}: {e}"
            )
            if attempt < max_retries:
                formatted_messages.append(
                    {
                        "role": "user",
                        "content": f"Your previous response did not conform to the required JSON schema ({str(e)}). Please output valid JSON matching the exact schema.",
                    }
                )
        except OpenAIError as e:
            logger.error(f"Azure OpenAI API error during json_chat(): {e}")
            raise RuntimeError(f"Azure OpenAI API error: {str(e)}") from e
        except Exception as e:
            logger.error(f"Unexpected error during json_chat(): {e}")
            raise RuntimeError(f"Unexpected LLM error: {str(e)}") from e

    raise ValueError(
        f"Failed to obtain valid JSON conforming to {schema_model.__name__} after {max_retries + 1} attempts. Last error: {str(last_error)}"
    )
